typography_spectrum: 0.8219647051300853
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.10283993720076978
  lightness: 0.23264309531077743
  saturation: 0.44632048020139337
  rhythmicContrast: 0.20602569379843771
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5668316136579961
analytics:
  google: null
  facebook: null
  twitter: null
name: 10thDot
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 360°Integrity
    url: 'https://thegrid.ai/360integrity/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fe8e5811-1eab-4599-a5b9-96a9ef3d8d92.jpg
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DsJw3xMGklJk&src=http%3A%2F%2Fwww.youtube.com%2Fembed%2FsJw3xMGklJk&type=text%2Fhtml&key=b7d04c9b404c499eba89ee7072e1c4f7&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'https://www.youtube.com/watch?v=sJw3xMGklJk&feature=youtu.be'
      keywords:
        - ''
      related: []
      author: []
      '@context': 'http://schema.org'
      title: YouTube
      '@type': VideoObject
      app_links: []
      publisher:
        url: 'http://youtube.com'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: www.youtube.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
purpose: []
